group_id: org.concopilot.example.copilot
artifact_id: basic-chat-copilot
version: 0.0.2

type: copilot
as_plugin: false

setup:
  pip:
    - concopilot>=0.0.3
  package: concopilot.basic.copilot

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  resource_manager:
    group_id: org.concopilot.basic.resource.manager
    artifact_id: basic-resource-manager
    version: 0.0.0
    config:
      resources:
        -
          group_id: org.concopilot.example.rwkv
          artifact_id: rwkv-model
          version: 0.0.2
          config:
            model_repo:
              local:
                model_path: null
              huggingface:
                repo_id: BlinkDL/rwkv-4-raven
                filename: RWKV-4-Raven-7B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230530-ctx8192.pth
                cache_dir: .hf_cache
                local_root: null
              modelscope:
                model_id: AI-ModelScope/rwkv-4-raven
                file_path: RWKV-4-Raven-7B-v12-Eng49%-Chn49%-Jpn1%-Other1%-20230530-ctx8192.pth
                cache_dir: .ms_cache
            rwkv_strategy: cuda fp16
            tokenizer_file: 20B_tokenizer.json
            tokenizer_url: https://raw.githubusercontent.com/BlinkDL/ChatRWKV/main/20B_tokenizer.json
            tokenizer_force_update: false
            max_tokens: 8192
        -
          group_id: org.concopilot.basic.resource.category
          artifact_id: disk
          version: 0.0.0

  cerebrum:
    group_id: org.concopilot.example.rwkv
    artifact_id: rwkv-cerebrum
    version: 0.0.2
    config:
      msg_retrieval_mode: ALL

  interactor:
    group_id: org.concopilot.example
    artifact_id: chat-interactor
    version: 0.0.2
    config:
      persist_history: false
      exit_tokens:
        - exit

  plugin_manager:
    group_id: org.concopilot.basic.plugin.manager
    artifact_id: basic-plugin-manager
    version: 0.0.0
    config:
      plugin_prompt_generator:
        group_id: org.concopilot.example.plugin_prompt_gen
        artifact_id: yaml-plugin-prompt-gen
        version: 0.0.0
      plugins: []

  message_manager:
    group_id: org.concopilot.basic.message.manager
    artifact_id: basic-json-msg-manager
    version: 0.0.0

  storage:
    group_id: org.concopilot.basic.storage
    artifact_id: disk-storage
    version: 0.0.1

  user_interface:
    group_id: org.concopilot.basic.interface
    artifact_id: cmd-user-interface
    version: 0.0.1
    config:
      user_msg_prefix: "USER:"
      non_user_msg_prefix: "ASSISTANT:"
      multiple_line_input: false
