group_id: org.concopilot.example.copilot
artifact_id: basic-chat-copilot
version: 0.0.3

type: copilot
as_plugin: false

setup:
  pip:
    - concopilot>=0.0.4
  package: concopilot.basic.copilot

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  resource_manager:
    group_id: org.concopilot.basic.resource.manager
    artifact_id: basic-resource-manager
    version: 0.0.0
    config:
      resources:
        -
          group_id: org.concopilot.example.zhipuai
          artifact_id: zhipuai-model
          version: 0.0.0
          config:
            # id: default
            # name: null
            base_url: https://open.bigmodel.cn/api/paas/v4
            base_url_secret_name: ZHIPUAI_BASE_URL
            api_key: null
            api_key_secret_name: ZHIPUAI_API_KEY
            timeout: null
            max_retries: 3
            custom_headers: {}
            model: glm-4
            default_chat_param: {}
        -
          group_id: org.concopilot.basic.resource.category
          artifact_id: disk
          version: 0.0.0

  cerebrum:
    group_id: org.concopilot.example.zhipuai
    artifact_id: zhipuai-cerebrum
    version: 0.0.0
    config:
      msg_retrieval_mode: ALL

  interactor:
    group_id: org.concopilot.example
    artifact_id: chat-interactor
    version: 0.0.3
    config:
      persist_history: false
      exit_tokens:
        - exit

  plugin_manager:
    group_id: org.concopilot.basic.plugin.manager
    artifact_id: basic-plugin-manager
    version: 0.0.0
    config:
      plugin_prompt_generator:
        group_id: org.concopilot.example.plugin_prompt_gen
        artifact_id: yaml-plugin-prompt-gen
        version: 0.0.0
      plugins: []

  message_manager:
    group_id: org.concopilot.basic.message.manager
    artifact_id: basic-json-msg-manager
    version: 0.0.0

  storage:
    group_id: org.concopilot.basic.storage
    artifact_id: disk-storage
    version: 0.0.1

  user_interface:
    group_id: org.concopilot.basic.interface
    artifact_id: cmd-user-interface
    version: 0.0.1
    config:
      user_msg_prefix: "USER:"
      non_user_msg_prefix: "ASSISTANT:"
      multiple_line_input: false
