group_id: org.concopilot.example.zhipuai
artifact_id: zhipuai-cerebrum
version: 0.0.0

type: cerebrum
as_plugin: false

setup:
  pip:
    - concopilot_examples>=0.0.4
  package: concopilot_examples.cerebrum.zhipuaicerebrum

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  # id: default
  name: GLM
  role: AI-Assistant
  max_tokens: null
  use_tool_call: false
  instruction_file: null # this will be ignored if the use_function_call is true, else the prompt described in this file with the full plugin list will be added into the GPT message list.
  msg_retrieval_mode: ALL
  instruction_prompt_role: system # this is the "role" used to compose the instruction messages
  flatten_asset_meta: true

  resources:
    -
      type: model
      id: default
