group_id: org.concopilot.example.rwkv
artifact_id: rwkv-cerebrum
version: 0.0.2

type: cerebrum
as_plugin: false

setup:
  pip:
    - concopilot_examples>=0.0.3
  package: concopilot_examples.cerebrum.rwkvcerebrum

url: https://github.com/concopilot/concopilot

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  # id: default
  name: Bob
  role: AI-Assistant
  max_tokens: null
  instruction_file: instruction.md
  msg_retrieval_mode: ALL

  resources:
    -
      type: model
      id: default
