group_id: org.concopilot.example.glm
artifact_id: glm-basic-model
version: 0.0.0

type: resource
as_plugin: false

resource_type: model

setup:
  pip:
    - concopilot_examples>=0.0.2
    - transformers>=4.30.2
    - numpy
    - torch>=2.0
    - sentencepiece
    - huggingface_hub
    - modelscope
  package: concopilot_examples.resource.category.model.glmmodel

url:

developers:
  -
    name: ZHONG Weikun
    id: xiaoshenxian
    url: https://github.com/xiaoshenxian

licenses:
  -
    name: The Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.txt

config:
  # id: default
  # name: null

  model_repo:
    local:
      repo_dir: null
    huggingface:
      repo_id: THUDM/chatglm3-6b
      repo_dir: .hf_repo
    modelscope:
      model_id: ZhipuAI/chatglm3-6b
      repo_dir: .ms_repo
      revision: v1.0.0

  transformers:
    auto_tokenizer:
      trust_remote_code: true

    auto_model:
      trust_remote_code: true
      device: cuda
